apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-01-29T11:34:26Z"
  generation: 1
  labels:
    app: mysql-deployment
  name: mysql-deployment
  namespace: default
  resourceVersion: "2007"
  selfLink: /apis/apps/v1/namespaces/default/deployments/mysql-deployment
  uid: 5d41c5f9-85e5-4716-9a37-769c54341c91
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mysql-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql-deployment
    spec:
      volumes:
      - name: mysql-pvc-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
    
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: MYSQL_ROOT_PASSWORD
              name: mysql-deployment-config-6voc
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              key: MYSQL_DATABASE
              name: mysql-deployment-config-6voc
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              key: MYSQL_USER
              name: mysql-deployment-config-6voc
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: MYSQL_PASSWORD
              name: mysql-deployment-config-6voc
        image: mysql:5.7
        imagePullPolicy: IfNotPresent
        name: mysql-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: mysql-pvc-storage
            subPath: mysql      
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2021-01-29T11:34:38Z"
    lastUpdateTime: "2021-01-29T11:34:38Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-01-29T11:34:26Z"
    lastUpdateTime: "2021-01-29T11:34:38Z"
    message: ReplicaSet "mysql-deployment-777fdbbf58" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
