apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-01-29T11:35:45Z"
  labels:
    app: mysql-deployment
  name: mysql-deployment-service
  namespace: default
  resourceVersion: "2293"
  selfLink: /api/v1/namespaces/default/services/mysql-deployment-service
  uid: c2db4d9f-e691-4959-9bc6-89bb30620350
spec:
  clusterIP: 10.8.3.99
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql-deployment
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
